# Generated by Django 5.2.12 on 2026-03-18 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='max_messenger',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Аккаунт МАХ'),
        ),
    ]
