# Generated by Django 5.2.12 on 2026-03-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0003_dogparent'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogparent',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активность'),
        ),
    ]
