# Generated by Django 5.2.12 on 2026-03-16 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0005_dogparent_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dogparent',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='dogparent',
            name='owner',
        ),
        migrations.AddField(
            model_name='dog',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активность'),
        ),
    ]
