# Generated by Django 5.2.12 on 2026-03-18 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0007_dog_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Просмотры'),
        ),
    ]
